export const LABEL_GUARDIAN_FULL_NAME = 'Parent / guardian full name';
export const LABEL_NEXT_OF_KIN_FULL_NAME = 'Next of kin full name';
export const LABEL_NEXT_OF_KIN_PHONE = 'Next of kin phone';
export const LABEL_NEXT_OF_KIN_EMAIL = 'Next of kin email (optional)';

export const GUARDIAN_RELATIONSHIPS = [
  'Mother',
  'Father',
  'Legal guardian',
  'Grandmother',
  'Grandfather',
  'Aunt',
  'Uncle',
  'Other',
] as const;

/** British first, then A–Z (common nationalities for UK registration forms). */
const NATIONALITIES_SORTED = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Angolan',
  'Argentine',
  'Australian',
  'Austrian',
  'Bangladeshi',
  'Belgian',
  'Brazilian',
  'Bulgarian',
  'Burmese',
  'Cameroonian',
  'Canadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Congolese',
  'Croatian',
  'Cypriot',
  'Czech',
  'Danish',
  'Dutch',
  'Egyptian',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Filipino',
  'Finnish',
  'French',
  'German',
  'Ghanaian',
  'Greek',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kenyan',
  'Korean',
  'Kuwaiti',
  'Latvian',
  'Lebanese',
  'Lithuanian',
  'Malaysian',
  'Mexican',
  'Moroccan',
  'Nepalese',
  'New Zealander',
  'Nigerian',
  'Norwegian',
  'Pakistani',
  'Palestinian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Romanian',
  'Russian',
  'Saudi',
  'Senegalese',
  'Serbian',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Somali',
  'South African',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Ugandan',
  'Ukrainian',
  'Emirati',
  'Venezuelan',
  'Vietnamese',
  'Yemeni',
  'Zimbabwean',
  'Other',
] as const;

export const NATIONALITIES = ['British', ...NATIONALITIES_SORTED] as const;
